# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.SlugField(max_length=20, unique=True, verbose_name='Short Link Text')),
                ('target', models.URLField(max_length=255, verbose_name='Target URL')),
            ],
        ),
    ]
