# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=1000)),
                ('uri', models.CharField(max_length=2000)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('remote_addr', models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ('link_text',)},
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='link_text',
            field=models.SlugField(help_text="Given the domain 'rtr.co', enter your shortlink text without slashes or spaces. Ex: 'red-dress'.", max_length=20, unique=True, verbose_name='Short Link Text'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='target',
            field=models.URLField(help_text='Enter a valid URL, including domain, where you want the shortlink to redirect to. Ex: http://www.renttherunway.com/the-really-long-link-to-the-red-dress-PDP', max_length=255, verbose_name='Target URL'),
        ),
        migrations.AlterUniqueTogether(
            name='shortlink',
            unique_together=set([('link_text', 'target')]),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='shortlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortlinks.ShortLink'),
        ),
    ]
